"""Bizzdesign Alfabet EDC (Excel Data Capture) workbooks: import as entities, export by
filling the template.

An EDC workbook is generated by Alfabet for one object class (here: Application). Besides
the visible data sheet it carries hidden machinery Alfabet needs to accept the file back:
``DCTDReference`` (column caption -> Alfabet property), ``ReferenceData*`` sheets behind
every picklist, and an ``ALFA_RUNTIME_DCT`` document property. So export never builds a
workbook from scratch -- it rewrites only the data rows of the user's own template and
copies every other part byte-for-byte.

* `read_edc(filename, bytes) -> payload` turns each data row into an application entity
  carrying its Alfabet ``Reference`` in ``_alfabet_ref``; Primary Capability and Platform
  become capability / IT-component entities. No model call is involved.
* `build_edc(template_name, template_bytes, payload) -> zip bytes` writes matched apps as
  ``Update`` rows (existing values kept wherever the payload is blank) and unmatched apps
  as ``Create`` rows, plus an ``alfabet_report.csv`` of everything a reviewer must check.

Values are never invented: a payload value with no exact picklist entry is left blank and
reported, and missing mandatory properties (Version, dates) are reported, not defaulted.

The mapping tables below are **the tenant-adaptation seam** for Alfabet, like
``leanix.SHEETS`` is for LeanIX. They are keyed by Alfabet property name (DCTD name), not
by column caption, because captions are configurable per template.
"""

from __future__ import annotations

import csv
import difflib
import html
import io
import re
import zipfile
from dataclasses import dataclass, field
from pathlib import PurePosixPath
from xml.etree import ElementTree as ET

from .ingest import UnsupportedFile

EDC_SUFFIXES = {".xlsx", ".xlsm"}
# Largest single workbook part we will inflate. A real 2,500-row template's data sheet is
# ~6 MB; the cap stops a zip bomb without getting in the way of genuine exports.
MAX_PART_BYTES = 64 * 1024 * 1024

_NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
_NS_R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
_M = "{%s}" % _NS

# EDC system columns: not Alfabet properties, so absent from DCTDReference.
_OPERATIONS = "Operations"
_REFERENCE = "Reference"

# ---------------------------------------------------------------------------
# Mapping seam: Alfabet picklist value <-> EATools enum
# ---------------------------------------------------------------------------

_CRITICALITY = {
    "Mission Critical": "mission_critical",
    "Business Critical": "business_critical",
    "Business Operational": "business_operational",
}
_OBJECT_STATE = {"Plan": "plan", "Active": "active", "Retired": "endOfLife"}
_LIFECYCLE_TO_STATE = {
    "plan": "Plan",
    "phaseIn": "Plan",
    "active": "Active",
    "phaseOut": "Active",
    "endOfLife": "Retired",
}
# Only one-to-one equivalents. "Externally Hosted" covers both SaaS and third-party data
# centres, and SaaS apps in practice sit under Externally *and* Cloud Hosted -- neither
# direction is safe to guess, so both stay unmapped (and are reported on export).
_HOSTING_TYPE = {"Cloud Hosted": "cloud", "Internally Hosted": "on_premise", "Hybrid": "hybrid"}


def _invert(mapping: dict[str, str]) -> dict[str, str]:
    return {v: k for k, v in mapping.items()}


# Export: Alfabet property -> getter over one application entity. Picklist columns are
# validated against the template's own reference data after the getter runs.
_EXPORT_FIELDS = {
    "Name": lambda app: app.get("name", ""),
    "SAG_Alias": lambda app: app.get("alias", ""),
    "Description": lambda app: app.get("description", ""),
    "Criticality": lambda app: _invert(_CRITICALITY).get(app.get("business_criticality", ""), ""),
    "ObjectState": lambda app: _LIFECYCLE_TO_STATE.get(app.get("lifecycle", ""), ""),
    "HostingType": lambda app: _invert(_HOSTING_TYPE).get(app.get("hosting", ""), ""),
}
# List-valued payload fields that feed a single-valued picklist: the first entry that
# exists in the picklist wins.
_EXPORT_PICK_FIRST = {
    "Domain": "capabilities",  # caption "Primary Capability"
    "ICTObject": "it_components",  # caption "Platform"
}
_STEREOTYPE = "Application"


class NotEdcWorkbook(UnsupportedFile):
    """An .xlsx that is not an Alfabet EDC export (or is too damaged to read)."""


def is_edc_filename(filename: str) -> bool:
    return PurePosixPath(filename.lower()).suffix in EDC_SUFFIXES


# ---------------------------------------------------------------------------
# Workbook reading
# ---------------------------------------------------------------------------

_ROW_RE = re.compile(r"<row\b([^>]*?)(?:/>|>(.*?)</row>)", re.S)
_CELL_RE = re.compile(r"<c\b([^>]*?)(?:/>|>(.*?)</c>)", re.S)
_ATTR_RE = re.compile(r'([\w:]+)="([^"]*)"')
_V_RE = re.compile(r"<v>(.*?)</v>", re.S)
_T_RE = re.compile(r"<t\b[^>]*>(.*?)</t>", re.S)
_EXCEL_ESC_RE = re.compile(r"_x([0-9A-Fa-f]{4})_")
_COL_RE = re.compile(r"[A-Z]+")


def _col_index(letters: str) -> int:
    n = 0
    for ch in letters:
        n = n * 26 + (ord(ch) - 64)
    return n


def _col_letters(index: int) -> str:
    out = ""
    while index:
        index, rem = divmod(index - 1, 26)
        out = chr(65 + rem) + out
    return out


def _decode(text: str) -> str:
    """XML-unescape, then undo Excel's _xHHHH_ escapes for control characters."""
    return _EXCEL_ESC_RE.sub(lambda m: chr(int(m.group(1), 16)), html.unescape(text))


@dataclass
class _Cell:
    col: str
    attrs: str  # raw attribute text, kept so styles survive a rewrite
    inner: str  # raw inner XML
    value: str  # decoded display value


@dataclass
class _Row:
    number: int
    attrs: str
    cells: dict[str, _Cell] = field(default_factory=dict)

    def get(self, col: str | None) -> str:
        if not col or col not in self.cells:
            return ""
        return self.cells[col].value


class EdcWorkbook:
    """A parsed EDC template. Holds the raw parts so export can rewrite just one sheet."""

    def __init__(self, filename: str, data: bytes) -> None:
        self.filename = filename
        try:
            self._zip = zipfile.ZipFile(io.BytesIO(data))
        except zipfile.BadZipFile:
            raise NotEdcWorkbook(f"{filename}: not a valid .xlsx file") from None
        for info in self._zip.infolist():
            if info.file_size > MAX_PART_BYTES:
                raise NotEdcWorkbook(f"{filename}: workbook part {info.filename} is too large")
        try:
            self._load()
        except (KeyError, ET.ParseError, ValueError, IndexError):
            raise NotEdcWorkbook(f"{filename}: unreadable workbook structure") from None

    # -- loading -------------------------------------------------------------

    def _text(self, part: str) -> str:
        return self._zip.read(part).decode("utf-8")

    def _load(self) -> None:
        self.shared_strings = self._read_shared_strings()
        wb = ET.fromstring(self._zip.read("xl/workbook.xml"))
        rels = ET.fromstring(self._zip.read("xl/_rels/workbook.xml.rels"))
        targets = {r.get("Id"): r.get("Target") for r in rels}

        self.sheets: dict[str, str] = {}  # sheet name -> part path
        visible: list[str] = []
        for sheet in wb.find(f"{_M}sheets"):
            target = targets[sheet.get(f"{{{_NS_R}}}id")]
            path = target.lstrip("/") if target.startswith("/") else f"xl/{target}"
            self.sheets[sheet.get("name")] = path
            if sheet.get("state") not in ("hidden", "veryHidden"):
                visible.append(sheet.get("name"))

        if "DCTDReference" not in self.sheets:
            raise NotEdcWorkbook(f"{self.filename}: not an Alfabet EDC workbook (no DCTDReference sheet)")

        self.defined_names = {
            dn.get("name"): (dn.text or "") for dn in wb.iter(f"{_M}definedName")
        }

        # caption -> Alfabet property name
        dctd_rows = self._rows("DCTDReference")
        self.caption_to_property = {
            r.get("C"): r.get("B") for r in dctd_rows[1:] if r.get("B") and r.get("C")
        }

        self.data_sheet = "Export" if "Export" in self.sheets else next(
            (n for n in visible if n != "Help"), None
        )
        if self.data_sheet is None:
            raise NotEdcWorkbook(f"{self.filename}: no data sheet found")
        self.sheet_xml = self._text(self.sheets[self.data_sheet])
        rows = self._parse_rows(self.sheet_xml)
        if not rows:
            raise NotEdcWorkbook(f"{self.filename}: data sheet is empty")
        self.header = rows[0]
        self.rows = [r for r in rows[1:] if any(c.value for c in r.cells.values())]

        # column letter <-> property (system columns keyed by caption)
        self.col_of: dict[str, str] = {}
        for col, cell in self.header.cells.items():
            caption = cell.value
            if caption in (_OPERATIONS, _REFERENCE):
                self.col_of[caption] = col
            elif caption in self.caption_to_property:
                self.col_of[self.caption_to_property[caption]] = col
        if "Name" not in self.col_of or _REFERENCE not in self.col_of:
            raise NotEdcWorkbook(f"{self.filename}: EDC data sheet lacks Name/Reference columns")

        self.picklists = self._read_picklists()
        self.mandatory = self._read_mandatory()

    def _read_shared_strings(self) -> list[str]:
        if "xl/sharedStrings.xml" not in self._zip.namelist():
            return []
        root = ET.fromstring(self._zip.read("xl/sharedStrings.xml"))
        out = []
        for si in root.findall(f"{_M}si"):
            # Plain <t> or rich-text runs <r><t>; skip phonetic <rPh> runs.
            parts = [t.text or "" for t in si.findall(f"{_M}t")]
            parts += [t.text or "" for r in si.findall(f"{_M}r") for t in r.findall(f"{_M}t")]
            out.append(_EXCEL_ESC_RE.sub(lambda m: chr(int(m.group(1), 16)), "".join(parts)))
        return out

    def _parse_rows(self, xml: str) -> list[_Row]:
        start = xml.find("<sheetData")
        end = xml.find("</sheetData>")
        if start == -1:
            return []
        body = xml[start:end] if end != -1 else xml[start:]
        rows = []
        for rm in _ROW_RE.finditer(body):
            attrs = rm.group(1)
            number = int(dict(_ATTR_RE.findall(attrs))["r"])
            row = _Row(number=number, attrs=attrs)
            for cm in _CELL_RE.finditer(rm.group(2) or ""):
                cattrs = dict(_ATTR_RE.findall(cm.group(1)))
                inner = cm.group(2) or ""
                col = _COL_RE.match(cattrs["r"]).group()
                row.cells[col] = _Cell(col, cm.group(1), inner, self._cell_value(cattrs.get("t"), inner))
            rows.append(row)
        return rows

    def _cell_value(self, cell_type: str | None, inner: str) -> str:
        if cell_type == "inlineStr":
            return _decode("".join(_T_RE.findall(inner)))
        v = _V_RE.search(inner)
        if v is None:
            return ""
        if cell_type == "s":
            return self.shared_strings[int(v.group(1))]
        return _decode(v.group(1))

    def _rows(self, sheet_name: str) -> list[dict[str, str]]:
        return [
            {col: cell.value for col, cell in row.cells.items()}
            for row in self._parse_rows(self._text(self.sheets[sheet_name]))
        ]

    def _read_picklists(self) -> dict[str, list[str]]:
        """Data-sheet column letter -> allowed values, via validation -> defined name -> range."""
        ref_cache: dict[str, dict[int, dict[str, str]]] = {}
        out: dict[str, list[str]] = {}
        for dv in re.finditer(r"<dataValidation\b([^>]*)>(.*?)</dataValidation>", self.sheet_xml, re.S):
            attrs = dict(_ATTR_RE.findall(dv.group(1)))
            if attrs.get("type") != "list":
                continue
            formula = re.search(r"<formula1>(.*?)</formula1>", dv.group(2), re.S)
            if not formula:
                continue
            target = self.defined_names.get(html.unescape(formula.group(1)).strip())
            m = re.match(r"'?(.+?)'?!\$([A-Z]+)\$(\d+):\$([A-Z]+)\$(\d+)$", target or "")
            if not m or m.group(1) not in self.sheets:
                continue
            sheet, col, first, last = m.group(1), m.group(2), int(m.group(3)), int(m.group(5))
            if sheet not in ref_cache:
                ref_cache[sheet] = {
                    r.number: {c: cell.value for c, cell in r.cells.items()}
                    for r in self._parse_rows(self._text(self.sheets[sheet]))
                }
            values = [
                ref_cache[sheet].get(n, {}).get(col, "") for n in range(first, last + 1)
            ]
            allowed = [v for v in values if v]
            for col_ref in attrs.get("sqref", "").split():
                out[_COL_RE.match(col_ref).group()] = allowed
        return out

    def _read_mandatory(self) -> list[str]:
        """Captions the Help sheet marks Mandatory=True (empty if there is no Help sheet)."""
        if "Help" not in self.sheets:
            return []
        rows = self._rows("Help")
        return [r.get("A", "") for r in rows[1:] if r.get("C", "").strip().lower() == "true"]

    # -- helpers -------------------------------------------------------------

    def caption(self, prop: str) -> str:
        col = self.col_of.get(prop)
        return self.header.get(col) if col else prop

    def picklist_match(self, prop: str, value: str) -> str | None:
        """Exact picklist spelling for `value`, or None. Free-text columns accept anything.

        Matching is case-insensitive and also ignores a leading ordinal ("8 Platform
        Delivered Services" == "Platform Delivered Services"), which Alfabet domains carry.
        """
        col = self.col_of.get(prop)
        allowed = self.picklists.get(col) if col else None
        if allowed is None:
            return value
        key = value.strip().casefold()
        for option in allowed:
            if option.strip().casefold() == key:
                return option
        for option in allowed:
            if re.sub(r"^\d+(\.\d+)*\s+", "", option.strip()).casefold() == key:
                return option
        return None


# ---------------------------------------------------------------------------
# Import
# ---------------------------------------------------------------------------


def _base_name(name: str) -> str:
    """'ADP Workforce Now (NTT GN)' -> 'ADP Workforce Now'. Alfabet suffixes the owning org."""
    return re.sub(r"\s*\([^()]*\)\s*$", "", name).strip()


def _payload_from_records(records: list[dict], source: str, summary: str) -> dict:
    """Normalised Alfabet application records -> an extraction-shaped payload.

    A record carries Alfabet *values* under neutral keys: name, ref, alias, shortname,
    description, criticality, objectstate, hostingtype, capability, platform, evidence.
    Both the EDC reader and the REST import produce these, so both map identically.
    """
    applications: list[dict] = []
    capabilities: dict[str, dict] = {}
    components: dict[str, dict] = {}
    for rec in records:
        name = (rec.get("name") or "").strip()
        if not name:
            continue
        capability = (rec.get("capability") or "").strip()
        if capability and capability not in capabilities:
            capabilities[capability] = {
                "name": capability,
                "description": "",
                "level": 1,
                "parent": "",
                "evidence": "Alfabet primary capability",
                "confidence": "high",
                "_source": source,
            }
        platform = (rec.get("platform") or "").strip()
        if platform and platform not in components:
            components[platform] = {
                "name": platform,
                "description": "",
                "category": "unknown",
                "evidence": "Alfabet platform (ICT object)",
                "confidence": "high",
                "_source": source,
            }

        # Extra names this app may appear under in a diagram. merge.py only links on them
        # when exactly one entity claims the name.
        match_names = [(rec.get("shortname") or "").strip()]
        base = _base_name(name)
        if base != name:
            match_names.append(base)

        applications.append(
            {
                "name": name,
                "alias": (rec.get("alias") or "").strip(),
                "description": (rec.get("description") or "").strip(),
                "business_criticality": _CRITICALITY.get((rec.get("criticality") or "").strip(), "unknown"),
                "lifecycle": _OBJECT_STATE.get((rec.get("objectstate") or "").strip(), "unknown"),
                "hosting": _HOSTING_TYPE.get((rec.get("hostingtype") or "").strip(), "unknown"),
                "capabilities": [capability] if capability else [],
                "data_objects": [],
                "it_components": [platform] if platform else [],
                "evidence": rec.get("evidence", ""),
                "confidence": "high",
                "_source": source,
                "_alfabet_ref": (rec.get("ref") or "").strip(),
                "_match_names": [n for n in match_names if n],
            }
        )

    return {
        "diagram_summary": summary.format(count=len(applications)),
        "applications": applications,
        "capabilities": list(capabilities.values()),
        "it_components": list(components.values()),
        "data_objects": [],
        "interfaces": [],
        "open_questions": [],
    }


def read_edc(filename: str, data: bytes) -> dict:
    """Turn an EDC workbook into an extraction-shaped payload (no model call)."""
    wb = EdcWorkbook(filename, data)
    col = wb.col_of.get
    records = []
    for row in wb.rows:
        ref = row.get(col(_REFERENCE)).strip()
        records.append(
            {
                "name": row.get(col("Name")),
                "ref": ref,
                "alias": row.get(col("SAG_Alias")),
                "shortname": row.get(col("ShortName")),
                "description": row.get(col("Description")),
                "criticality": row.get(col("Criticality")),
                "objectstate": row.get(col("ObjectState")),
                "hostingtype": row.get(col("HostingType")),
                "capability": row.get(col("Domain")),
                "platform": row.get(col("ICTObject")),
                "evidence": f"Alfabet {wb.data_sheet} row {row.number}" + (f" (Reference {ref})" if ref else ""),
            }
        )
    payload = _payload_from_records(records, filename, f"Alfabet EDC import: {{count}} applications from {filename}.")
    if not payload["applications"]:
        raise NotEdcWorkbook(f"{filename}: EDC workbook has no named rows")
    return payload


# Alfabet REST report rows: `Values` keys are the report's lower-case column names.
# Observed in the Application-Mark report; a column the report lacks (it has no
# criticality) simply comes back blank and maps to "unknown".
_API_VALUE_KEYS = {
    "name": "name",
    "alias": "alias",
    "shortname": "shortname",
    "description": "description",
    "criticality": "criticality",
    "objectstate": "objectstate",
    "hostingtype": "hostingtype",
    "capability": "primarycapability",
    "platform": "platform",
}


def payload_from_api(objects: list[dict], source: str) -> dict:
    """Alfabet REST `Objects` (ClassName/RefStr/Values) -> an extraction-shaped payload."""
    records = []
    for obj in objects:
        if not isinstance(obj, dict) or obj.get("ClassName", "Application") != "Application":
            continue
        values = obj.get("Values") or {}
        rec = {key: _api_text(values.get(api_key)) for key, api_key in _API_VALUE_KEYS.items()}
        rec["ref"] = _api_text(obj.get("RefStr"))
        rec["evidence"] = f"Alfabet API, {source}" + (f" (Reference {rec['ref']})" if rec["ref"] else "")
        records.append(rec)
    return _payload_from_records(records, source, f"Alfabet API import: {{count}} applications ({source}).")


def _api_text(value) -> str:
    return "" if value is None else str(value)


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------


@dataclass
class _Issue:
    name: str
    operation: str
    reference: str
    issue: str


class _SharedStrings:
    """Append-only view over the template's shared-string table."""

    def __init__(self, existing: list[str]) -> None:
        self.count = len(existing)
        self.index = {s: i for i, s in enumerate(existing)}
        self.added: list[str] = []

    def get(self, text: str) -> int:
        if text not in self.index:
            self.index[text] = self.count + len(self.added)
            self.added.append(text)
        return self.index[text]


def _xml_text(text: str) -> str:
    # Control characters other than tab/newline are illegal in XML; Excel's escape keeps them.
    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f]", lambda m: f"_x{ord(m.group()):04X}_", text)
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _app_values(app: dict, wb: EdcWorkbook, issues: list[str]) -> dict[str, str]:
    """Alfabet property -> value for one application; unmappable values reported, not guessed."""
    values: dict[str, str] = {}
    for prop, getter in _EXPORT_FIELDS.items():
        if prop not in wb.col_of:
            continue
        value = str(getter(app) or "").strip()
        if not value:
            continue
        match = wb.picklist_match(prop, value)
        if match is None:
            issues.append(f"{wb.caption(prop)}: '{value}' is not in the template picklist; left unchanged")
            continue
        values[prop] = match

    hosting = app.get("hosting", "")
    if hosting not in ("", "unknown") and "HostingType" not in values:
        issues.append(f"Hosting '{hosting}' has no unambiguous Alfabet Hosting Type; left unchanged")
    crit = app.get("business_criticality", "")
    if crit not in ("", "unknown") and "Criticality" not in values:
        issues.append(f"Business criticality '{crit}' has no Alfabet equivalent; left unchanged")

    for prop, list_field in _EXPORT_PICK_FIRST.items():
        if prop not in wb.col_of:
            continue
        candidates = [c for c in app.get(list_field, []) if c]
        match = next((m for c in candidates if (m := wb.picklist_match(prop, c))), None)
        if match:
            values[prop] = match
        elif candidates:
            issues.append(
                f"{wb.caption(prop)}: none of {candidates} is in the template picklist; left unchanged"
            )
    return values


def _possible_duplicates(name: str, existing: list[tuple[str, set[str]]], cutoff: float = 0.8) -> list[str]:
    """Existing names close to `name`, also compared without their org suffix."""
    matcher = difflib.SequenceMatcher(None)
    matcher.set_seq2(name.casefold())
    scored = []
    for original, variants in existing:
        best = 0.0
        for variant in variants:
            matcher.set_seq1(variant)
            if matcher.real_quick_ratio() >= cutoff and matcher.quick_ratio() >= cutoff:
                best = max(best, matcher.ratio())
        if best >= cutoff:
            scored.append((-best, original))
    return [n for _, n in sorted(scored)[:3]]


def _cell_xml(col: str, row_number: int, style: str | None, text: str, strings: _SharedStrings) -> str:
    s = f' s="{style}"' if style else ""
    if not text:
        return f'<c r="{col}{row_number}"{s}/>'
    return f'<c r="{col}{row_number}"{s} t="s"><v>{strings.get(text)}</v></c>'


def _style_of(attrs: str) -> str | None:
    return dict(_ATTR_RE.findall(attrs)).get("s")


def _row_xml(number: int, row_attrs: str, cells: dict[str, str]) -> str:
    attrs = re.sub(r'\br="\d+"', f'r="{number}"', row_attrs, count=1)
    ordered = "".join(cells[c] for c in sorted(cells, key=_col_index))
    return f"<row{attrs}>{ordered}</row>"


def _renumber_cell(cell: _Cell, number: int) -> str:
    attrs = re.sub(r'\br="[A-Z]+\d+"', f'r="{cell.col}{number}"', cell.attrs, count=1)
    return f"<c{attrs}>{cell.inner}</c>" if cell.inner else f"<c{attrs}/>"


def build_edc(template_name: str, template_bytes: bytes, payload: dict) -> bytes:
    """Fill the EDC template with the payload's applications; return a zip (xlsx + report)."""
    wb = EdcWorkbook(template_name, template_bytes)
    strings = _SharedStrings(wb.shared_strings)
    col_of = wb.col_of
    by_ref = {r.get(col_of[_REFERENCE]).strip(): r for r in wb.rows if r.get(col_of[_REFERENCE]).strip()}
    existing_names = [
        (n, {n.casefold(), _base_name(n).casefold()})
        for n in (r.get(col_of["Name"]).strip() for r in wb.rows)
        if n
    ]
    # Create rows borrow per-column styles from the first data row (or the header).
    style_row = wb.rows[0] if wb.rows else wb.header
    style_for = {c: _style_of(cell.attrs) for c, cell in style_row.cells.items()}
    all_cols = sorted(set(wb.header.cells) | set(style_row.cells), key=_col_index)

    report: list[_Issue] = []
    out_rows: list[str] = []
    next_row = 2
    counts = {"Create": 0, "Update": 0, "unchanged": 0, "skipped": 0}

    for app in payload.get("applications", []):
        name = str(app.get("name", "")).strip()
        if not name:
            continue
        refs = [r.strip() for r in str(app.get("_alfabet_ref", "") or "").split(";") if r.strip()]
        notes: list[str] = []

        if len(refs) > 1:
            counts["skipped"] += 1
            report.append(_Issue(name, "Skipped", "; ".join(refs), "matches several Alfabet objects; keep one Reference in _alfabet_ref"))
            continue
        if refs and refs[0] not in by_ref:
            counts["skipped"] += 1
            report.append(_Issue(name, "Skipped", refs[0], "Reference not found in this template; export from the workbook it came from"))
            continue

        values = _app_values(app, wb, notes)

        if refs:
            existing = by_ref[refs[0]]
            changed = {
                prop: value
                for prop, value in values.items()
                if value.strip() != existing.get(col_of[prop]).strip()
            }
            if not changed:
                counts["unchanged"] += 1
                continue
            cells = {c: _renumber_cell(cell, next_row) for c, cell in existing.cells.items()}
            for prop, value in changed.items():
                col = col_of[prop]
                style = _style_of(existing.cells[col].attrs) if col in existing.cells else style_for.get(col)
                cells[col] = _cell_xml(col, next_row, style, value, strings)
                old = existing.get(col)
                notes.append(f"{wb.caption(prop)}: '{old}' -> '{value}'" if old else f"{wb.caption(prop)}: set to '{value}'")
            operation, ref, row_attrs = "Update", refs[0], existing.attrs
        else:
            values.setdefault("Name", name)
            if "Stereotype" in col_of and wb.picklist_match("Stereotype", _STEREOTYPE):
                values["Stereotype"] = wb.picklist_match("Stereotype", _STEREOTYPE)
            cells = {c: _cell_xml(c, next_row, style_for.get(c), "", strings) for c in all_cols}
            for prop, value in values.items():
                col = col_of[prop]
                cells[col] = _cell_xml(col, next_row, style_for.get(col), value, strings)
            filled = {wb.caption(p) for p in values}
            missing = [m for m in wb.mandatory if m not in filled]
            if missing:
                notes.append(f"mandatory in Alfabet, not known from the sources: {', '.join(missing)}")
            close = _possible_duplicates(name, existing_names)
            if close:
                notes.append(f"possible duplicate of existing: {'; '.join(close)}")
            operation, ref, row_attrs = "Create", "", style_row.attrs

        if _OPERATIONS in col_of:
            col = col_of[_OPERATIONS]
            cells[col] = _cell_xml(col, next_row, style_for.get(col), operation, strings)
        counts[operation] += 1
        out_rows.append(_row_xml(next_row, row_attrs, cells))
        for note in notes or ["ok"]:
            report.append(_Issue(name, operation, ref, note))
        next_row += 1

    xlsx = _rewrite_workbook(wb, out_rows, strings, last_row=next_row - 1)
    stem = PurePosixPath(template_name).stem or "alfabet"
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{stem}_EATools.xlsx", xlsx)
        zf.writestr("alfabet_report.csv", _report_csv(report, counts))
    return buf.getvalue()


def _rewrite_workbook(wb: EdcWorkbook, out_rows: list[str], strings: _SharedStrings, last_row: int) -> bytes:
    """Copy the template, replacing only the data rows and appending new shared strings."""
    xml = wb.sheet_xml
    header_match = next(m for m in _ROW_RE.finditer(xml) if dict(_ATTR_RE.findall(m.group(1))).get("r") == "1")
    start = xml.index(">", xml.index("<sheetData")) + 1
    end = xml.index("</sheetData>")
    xml = xml[:start] + header_match.group(0) + "".join(out_rows) + xml[end:]
    last_col = max((_col_index(c) for c in wb.header.cells), default=1)
    xml = re.sub(r'<dimension ref="[^"]*"/>', f'<dimension ref="A1:{_col_letters(last_col)}{max(last_row, 1)}"/>', xml, count=1)
    # Hyperlinks and their anchors belonged to the replaced rows.
    xml = re.sub(r"<hyperlinks>.*?</hyperlinks>", "", xml, count=1, flags=re.S)

    sst_part = "xl/sharedStrings.xml"
    if sst_part not in wb._zip.namelist():
        raise NotEdcWorkbook(f"{wb.filename}: template has no shared-string table")
    sst = wb._text(sst_part)
    if strings.added:
        added = "".join(f'<si><t xml:space="preserve">{_xml_text(s)}</t></si>' for s in strings.added)
        sst = sst.replace("</sst>", added + "</sst>")
    total = strings.count + len(strings.added)
    # `count` (total references) is optional and now unknowable without a full recount.
    sst = re.sub(r'\s+count="\d+"', "", sst, count=1)
    sst = re.sub(r'uniqueCount="\d+"', f'uniqueCount="{total}"', sst, count=1)

    replaced = {wb.sheets[wb.data_sheet]: xml.encode("utf-8"), sst_part: sst.encode("utf-8")}
    out = io.BytesIO()
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for info in wb._zip.infolist():
            data = replaced.get(info.filename)
            zf.writestr(info, data if data is not None else wb._zip.read(info.filename))
    return out.getvalue()


def _report_csv(report: list[_Issue], counts: dict[str, int]) -> bytes:
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["Name", "Operation", "Reference", "Issue"])
    for item in report:
        writer.writerow([item.name, item.operation, item.reference, item.issue])
    writer.writerow([])
    writer.writerow(
        [f"Totals: {counts['Create']} create, {counts['Update']} update, "
         f"{counts['unchanged']} matched but unchanged (omitted), {counts['skipped']} skipped"]
    )
    return b"\xef\xbb\xbf" + buf.getvalue().encode("utf-8")
